---
sidebar: sidebar 
permalink: oci/add-credentials-oci.html 
keywords: permissions, policy, iam, iam role, role, granting, iam policy, iam user, access keys, arn, aws accounts, aws, aws profile, json, credentials, adding credentials, add credentials, oci nss, oracle cloud infrastructure 
summary: Oracle Cloud Infrastructure（OCI）の認証情報を追加して、Workload Factory が OCI アカウント内のクラウド リソースをデプロイおよび管理するために必要な権限を付与します。 
---
= NetApp Workload FactoryにOracle Cloud Infrastructureの認証情報を追加する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
クラウド プロバイダの認証情報を追加および管理して、NetApp Workload Factoryがクラウド プロバイダアカウント内のリソースをデプロイおよび管理するために必要な権限を持てるようにします。

link:permissions-oci.html["OCI NetApp ストレージサービスの権限"]

.タスク概要
既存のWorkload Factoryアカウントに認証情報を追加するには、「認証情報」ページを使用します。これにより、Workload Factoryは、お客様のクラウド環境内のリソースとプロセスを管理するために必要な権限を取得します。

.開始する前に
Oracle Cloud Infrastructureアカウントにログインするには、認証情報が必要です。

.手順
.  https://console.netapp.com/["NetAppコンソール"^]にログインします。
. メニューから、*ワークロード* > *管理* > *認証情報* を選択します。
. 認証情報ページで、「認証情報の追加」を選択します。
. Oracle Cloud Infrastructure NetApp Storage Serviceの認証情報の追加ページで、次の手順を実行します：
+
.. 「権限構成」で、Oracle Cloud Infrastructure NetApp Storage Serviceの認証情報に適切な権限を選択します。*View, plan, and analyze*の権限がデフォルトです。この権限ポリシーにより、OCI NSSストレージプールを表示したり、システムの状態を把握したり、システムの適切なアーキテクチャ分析を取得したり、コスト削減の可能性を探ったりすることができます。
.. Oracle Cloud Consoleで提供される手動の手順に従って、OCI NSS認証情報の権限構成を完了してください。
.. 「認証情報名」に、これらの認証情報に使用する名前を入力し、テナントOCIDを入力します。


. *追加*を選択します。


.次の手順
link:quick-start-oci.html["Oracle Cloud Infrastructure NetApp ストレージサービスのクイックスタート（NetApp Workload Factory 環境）。"]
