---
sidebar: sidebar 
permalink: fsx-storage/create-discover-systems.html 
keywords: Amazon FSx for NetApp ONTAP, fsx, volumes, create system, delete system, access key, secret key, region, availability zones, discover, storage capacity, iops, throughput, security group, security, NetApp Console 
summary: クラウド ストレージ システムを作成または検出して、NetApp Consoleからボリュームや追加のデータサービスを追加および管理します。 
---
= NetApp Consoleでクラウドストレージシステムを作成または検出する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
クラウド ストレージ システムを作成または検出して、NetApp Consoleからボリュームや追加のデータサービスを追加および管理します。



[[create-a-storage-system]]
== ストレージシステムを作成する

最初のステップは、ストレージシステムを作成することです。クラウド プロバイダのコンソールですでにストレージシステムを作成している場合は、<<既存のクラウドストレージシステムを検出する,NetApp Consoleを使用して検出する>>。

.タスク概要
ストレージVMは、ファイルシステムを作成する際に作成されます。

.開始する前に
FSx for ONTAPファイルシステムを作成する前に、以下が必要です：

* Workload Factory に FSx for ONTAP ファイルシステムを作成するために必要な権限を付与する IAM ロールの ARN。link:permissions-reference-fsx.html["AWS アカウントに権限を付与する方法を説明します"^]。
* FSx for ONTAPインスタンスを作成するリージョンとVPCの情報。




[[create-an-fsx-for-ontap-file-system]]
== FSx for ONTAPファイルシステムを作成します

_Quick create_ または _Advanced create_ を使用して、FSx for ONTAPファイルシステムを作成できます。Codeboxで利用できる以下のツールも使用できます：REST API、CloudFormation、Terraform。link:../admin/use-codebox.html#how-to-use-codebox["Codeboxを使用した自動化の方法について学習します"^]。


NOTE: CodeboxからTerraformを使用する場合、コピーまたはダウンロードしたコードでは `fsxadmin`および `vsadmin`のパスワードが非表示になります。コードを実行する際には、パスワードを再入力する必要があります。

[role="tabbed-block"]
====
.クイック作成
--
クイック作成を使用すると、推奨されるベストプラクティス構成を利用できます。FSx for ONTAPファイルシステムを作成したあと、ほとんどの設定を変更できます。

.手順
. NetApp Consoleメニューから、*ストレージ*、次に*管理*を選択します。
. システムページから *システムの追加* を選択します。
. 場所として「Amazon Web Services」を選択し、Amazon FSx for NetApp ONTAPの「新規追加」を選択します。
. Create FSx for ONTAP ファイルシステムページで、*クイック作成*を選択します。
+
保存済みの設定を読み込むこともできます。

. ファイルシステムの一般設定で、以下を入力してください：
+
.. *AWS認証情報*：Workload FactoryにAWS認証情報を追加するか、認証情報なしで続行するかを選択してください。
.. *ファイルシステム名*：ファイルシステムの名前を入力してください。
.. *リージョンとVPC*：ファイルシステムのリージョンとVPCを選択します。
.. *展開タイプ*：展開タイプを選択してください。
+
*** シングルアベイラビリティゾーン（Single-AZ）展開：ハードウェア障害を監視し、障害発生時にインフラストラクチャコンポーネントを自動的に交換することで可用性を提供します。アベイラビリティゾーン内でデータを自動的に複製することで、コンポーネントの障害からデータを保護し、高い耐久性を実現します。
+
この構成は、高性能なワークロード、またはワークロードが小規模から始まり、スループット72 GB/s、2.4 million IOPSまで段階的に拡張する場合に推奨されます。

*** 複数のアベイラビリティゾーン（マルチAZ）展開：アベイラビリティゾーンが利用不能になった場合でも、データへの継続的な可用性を提供します。マルチAZファイルシステムは、共有ONTAPファイルデータへの高可用性を必要とし、アベイラビリティゾーン間の組み込みレプリケーションを備えたストレージを必要とする、ビジネス クリティカルな本番ワークロード向けに設計されています。
+
この単一のHAペア構成は、最大6 GB/sのスループットまたは200,000 IOPSを必要とするワークロードに推奨されます。



.. *タグ*：オプションで、最大50個のタグを追加できます。


. 「ファイルシステムの詳細」欄に、以下の情報を入力してください：
+
.. *SSDストレージ容量*：ストレージ容量を入力し、ストレージ容量の単位を選択してください。
+
*** 第一世代の導入では、ファイルシステム作成後に容量を減らすことはできません。
*** 第2世代の導入においては、ファイルシステム作成後に容量を増やすことができます。


.. *ONTAP認証情報*：オプション。ONTAPのユーザー名とパスワードを入力してください。パスワードは今すぐ設定することも、後で設定することもできます。
+
指定したユーザーがfsxadminユーザーでない場合、後でfsxadminのパスワードをリセットする必要が生じた場合は、AWSコンソールからリセットできます。

.. *SMB/CIFS 設定*：オプション。SMB/CIFSプロトコルを使用してボリュームにアクセスする場合は、ファイルシステムの作成時にストレージVMのActive Directoryを構成する必要があります。このファイルシステム用に作成されるストレージVMについて、以下の詳細情報を提供してください。
+
... *参加するActive Directoryドメイン*：Active Directoryの完全修飾ドメイン名（FQDN）を入力してください。
... *DNS IPアドレス*：カンマで区切って、最大3つのDNS IPアドレスを入力してください。
... *SMBサーバーのNetBIOS名*：ストレージVM用に作成するActive DirectoryコンピューターオブジェクトのSMBサーバーのNetBIOS名を入力します。これは、Active DirectoryにおけるこのストレージVMの名前です。
... *ユーザー名*：既存のActive Directoryに登録されているサービスアカウントのユーザー名を入力してください。
+
ドメインの接頭辞や接尾辞は含めないでください。 `EXAMPLE\ADMIN`には、 `ADMIN`を使用します。

... *パスワード*：サービスアカウントのパスワードを入力してください。
... *組織単位*：必要に応じて、FSx for ONTAPのコンピュータアカウントを作成する組織単位の名前を入力します。OUは、ファイルシステムを参加させる組織単位の識別パス名です。
... *委任管理者グループ*：必要に応じて、ファイルシステムを管理できる Active Directory 内のグループ名を入力します。
+
AWS Managed Microsoft AD を使用している場合は、AWS Delegated FSx Administrators、AWS Delegated Administrators、またはOU への権限を委任したカスタムグループなどのグループを指定する必要があります。

+
自己管理型のADに参加する場合は、AD内のグループ名を使用してください。デフォルトのグループは `Domain Admins`です。





. 定義した設定を確認するには、「概要」を開いてください。必要に応じて、ファイルシステムを保存または作成する前に、この時点で設定を変更できます。
. ファイルシステムを保存または作成します。


.結果
ファイルシステムを作成した場合、新しいFSx for ONTAP設定がシステムページに表示されます。

FSx for ONTAPファイルシステムは、NetApp Consoleのワークロードからの管理、ONTAP System Managerの使用、AWS CloudFormationの使用など、いくつかの方法で管理できます。

--
.高度な作成
--
高度な作成機能を使用すると、可用性、セキュリティ、バックアップ、メンテナンスなど、すべての構成オプションを設定できます。

.手順
. NetApp Consoleメニューから、*ストレージ*、次に*管理*を選択します。
. システムページから *システムの追加* を選択します。
. 場所として「Amazon Web Services」を選択し、Amazon FSx for NetApp ONTAPの「新規追加」を選択します。
. Create FSx for ONTAPファイルシステムページで、*詳細作成*を選択します。
+
保存済みの設定を読み込むこともできます。

. ファイルシステムの一般設定で、以下を入力してください：
+
.. *AWS認証情報*：Workload FactoryにAWS認証情報を追加するか、認証情報なしで続行するかを選択してください。
.. *ファイルシステム名*：ファイルシステムの名前を入力してください。
.. *リージョンとVPC*：ファイルシステムのリージョンとVPCを選択します。
.. *展開タイプ*：展開タイプとファイルシステムの世代を選択してください。第2世代ファイルシステムの利用可否は、選択したリージョンによって異なります。選択したリージョンが第2世代のFSx for ONTAPファイルシステムをサポートしていない場合、展開タイプは第1世代に切り替わります。
+
*** シングルアベイラビリティゾーン（Single-AZ）展開：ハードウェア障害を監視し、障害発生時にインフラストラクチャコンポーネントを自動的に交換することで可用性を提供します。アベイラビリティゾーン内でデータを自動的に複製することで、コンポーネントの障害からデータを保護し、高い耐久性を実現します。
+
*ファイルシステム生成*：次のいずれかを選択してください：

+
**** *第2世代*：この構成は、高性能ワークロード、またはワークロードが小規模から始まり、72 GB/sのスループットと2.4 million IOPSまで段階的にスケールアウトする場合に推奨されます。
**** *第1世代*：この構成は、最大4 GB/sまたは160,000 IOPSを必要とするワークロードに最適です。第1世代のファイルシステムは、容量を増やすことしかできません。


*** 複数のアベイラビリティゾーン（マルチAZ）展開：アベイラビリティゾーンが利用不能になった場合でも、データへの継続的な可用性を提供します。マルチAZファイルシステムは、共有ONTAPファイルデータへの高可用性を必要とし、アベイラビリティゾーン間の組み込みレプリケーションを備えたストレージを必要とする、ビジネス クリティカルな本番ワークロード向けに設計されています。
+
*ファイルシステム生成*：次のいずれかを選択してください：

+
**** *第2世代*：このシングルHAペア構成は、最大6 GB/sのスループットまたは200,000 IOPSを必要とするワークロードに推奨されます。マルチAZ構成の第2世代ファイルシステムでは、ワークロードの需要に合わせて容量を増減させることができます。
**** *第1世代*：この構成は、最大4 GB/sまたは160,000 IOPSを必要とするワークロードに最適です。第1世代のファイルシステムは、容量を増やすことしかできません。




.. *タグ*：オプションで、最大50個のタグを追加できます。


. ファイルシステムの詳細欄に、以下の情報を入力してください：
+
.. *SSDストレージ容量*：ストレージ容量を入力し、ストレージ容量の単位を選択してください。
+
*** 第一世代の導入では、ファイルシステム作成後に容量を減らすことはできません。
*** 第2世代の導入では、容量を調整できます。


.. *HAペアあたりのスループット容量*：HAペアの数あたりのスループット容量を選択します。第一世代のファイルシステムは、HAペアを1つしかサポートしていません。
.. *プロビジョニング済みIOPS*：次のいずれかのオプションを選択してください：
+
*** *自動*：自動設定の場合、作成される GiB ごとに 3 IOPS が追加されます。
*** *ユーザープロビジョニング*：ユーザープロビジョニングの場合は、IOPS値を入力してください。


.. *ONTAP認証情報*：オプション。ONTAPのユーザー名とパスワードを入力してください。パスワードは今すぐ設定することも、後で設定することもできます。
+
指定したユーザーがfsxadminユーザーでない場合、後でfsxadminのパスワードをリセットする必要が生じた場合は、AWSコンソールからリセットできます。

.. *ストレージVMの認証情報*：オプション。ユーザー名を入力してください。パスワードは、このファイルシステム固有のものにすることも、ONTAPの認証情報として入力したのと同じパスワードを使用することもできます。パスワードは今すぐ設定することも、後で設定することもできます。
.. *SMB/CIFS 設定*：オプション。SMB/CIFSプロトコルを使用してボリュームにアクセスする場合は、ファイルシステムの作成時にストレージVMのActive Directoryを構成する必要があります。このファイルシステム用に作成されるストレージVMについて、以下の詳細情報を提供してください。
+
... *参加するActive Directoryドメイン*：Active Directoryの完全修飾ドメイン名（FQDN）を入力してください。
... *DNS IPアドレス*：カンマで区切って、最大3つのDNS IPアドレスを入力してください。
... *SMBサーバーのNetBIOS名*：ストレージVM用に作成するActive DirectoryコンピューターオブジェクトのSMBサーバーのNetBIOS名を入力します。これは、Active DirectoryにおけるこのストレージVMの名前です。
... *ユーザー名*：既存のActive Directoryに登録されているサービスアカウントのユーザー名を入力してください。
+
ドメインの接頭辞や接尾辞は含めないでください。 `EXAMPLE\ADMIN`には、 `ADMIN`を使用します。

... *パスワード*：サービスアカウントのパスワードを入力してください。
... *組織単位*：必要に応じて、FSx for ONTAPのコンピュータアカウントを作成する組織単位の名前を入力します。OUは、ファイルシステムを参加させる組織単位の識別パス名です。
... *委任管理者グループ*：必要に応じて、ファイルシステムを管理できる Active Directory 内のグループ名を入力します。
+
AWS Managed Microsoft AD を使用している場合は、AWS Delegated FSx Administrators、AWS Delegated Administrators、またはOU への権限を委任したカスタムグループなどのグループを指定する必要があります。

+
自己管理型のADに参加する場合は、AD内のグループ名を使用してください。デフォルトのグループは `Domain Admins`です。





. 「ネットワークとセキュリティ」の項目で、以下の情報を提供してください：
+
.. *セキュリティグループ*：セキュリティグループを作成するか、既存のセキュリティグループを使用します。
+
新しいセキュリティグループについては、セキュリティグループのプロトコル、ポート、および役割の説明について<<Security group details,セキュリティグループの詳細>>を参照してください。

.. *アベイラビリティゾーン*：アベイラビリティゾーンとサブネットを選択します。
+
*** クラスタ構成ノード1の場合：可用性ゾーンとサブネットを選択します。
*** クラスタ構成ノード2の場合：可用性ゾーンとサブネットを選択します。


.. *VPC ルート テーブル*：クライアントがボリュームにアクセスできるようにするには、VPC ルート テーブルを選択します。
.. *エンドポイントIPアドレス範囲*：*VPC外のフローティングIPアドレス範囲*または*IPアドレス範囲を入力*を選択し、IPアドレス範囲を入力します。
.. *暗号化*：ドロップダウンから暗号化キー名を選択します。


. バックアップとメンテナンスの項目で、以下の情報を提供してください：
+
.. *ボリュームバックアップ*：日次自動バックアップはデフォルトで有効になっています。必要に応じて無効にしてください。
+
... *自動バックアップの保持期間*：自動バックアップを保持する日数を入力してください。
... *日次自動バックアップウィンドウ*：*設定なし*（日次バックアップの開始時刻が自動的に選択されます）または *日次バックアップの開始時刻を選択* を選択して開始時刻を指定します。


.. *週次メンテナンスウィンドウ*：*指定なし*（週次メンテナンスウィンドウの開始時刻が自動的に選択されます）または*30分間の週次メンテナンスウィンドウの開始時刻を選択*を選択して開始時刻を指定します。


. ファイルシステムを保存または作成します。


.結果
ファイルシステムを作成した場合、新しいFSx for ONTAP設定がシステムページに表示されます。

FSx for ONTAPファイルシステムは、NetApp Consoleのワークロードからの管理、ONTAP System Managerの使用、AWS CloudFormationの使用など、いくつかの方法で管理できます。

--
====


[[discover-an-existing-cloud-storage-system]]
== 既存のクラウドストレージシステムを検出する

以前にWorkload Factoryでクラウド ストレージ プロバイダの認証情報を提供している場合は、Discoverable systemsページからストレージシステムを自動的に検出できます。利用可能なデータサービスを確認することもできます。

.タスク概要
クラウドストレージシステムは、アカウント内で一度だけ検出でき、1つのワークスペースにのみ関連付けることができます。ストレージシステムは後で削除して、別のワークスペースに再関連付けすることができます。

.手順
. NetApp Consoleメニューから、*ストレージ*、*管理*、*Discoverable systems*の順に選択します。
. 検出されたクラウドストレージシステムの数が表示されます。*検出*を選択します。
. 1つ以上のストレージシステムを選択し、*検出*を選択してシステムページに追加します。


[NOTE]
====
* 名前のないストレージシステムを選択した場合、システムの名前を入力するよう求められます。
* コンソールから管理に必要な認証情報を持たないストレージシステムを選択した場合、必要な権限を持つ認証情報を選択するよう促されます。
* 以下のリージョンは検出をサポートしていません：中国リージョン、GovCloud（米国）リージョン、Secret Cloud、およびTop Secret Cloud。


====
.結果
コンソールは、検出されたシステムを「システム」ページに表示します。ストレージシステムは、NetApp Consoleのワークロードからの管理、ONTAP System Managerの使用、またはクラウド プロバイダのストレージ管理ツールの使用など、さまざまな方法で管理できます。
