---
sidebar: sidebar 
permalink: gcnv/add-credentials.html 
keywords: permissions, policy, iam, iam role, role, granting, iam policy, iam user, access keys, arn, aws accounts, aws, aws profile, json, credentials, adding credentials, add credentials 
summary: Workload Factoryがお客様のGoogleアカウントでクラウドリソースをデプロイおよび管理するために必要な権限を取得できるように、Google Cloud NetApp Volumesの認証情報を追加します。 
---
= Google Cloud NetApp Volumesの認証情報をNetApp Workload Factoryに追加します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
クラウド プロバイダの認証情報を追加および管理して、NetApp Workload Factoryがクラウド プロバイダアカウント内のリソースをデプロイおよび管理するために必要な権限を持てるようにします。



[[overview]]
== 概要

NetAppコンソールの認証情報ページから、Google Cloud NetApp Volumesの認証情報を追加できます。コンソールには、ガイド付きのセットアップ手順とドキュメントへのリンクが用意されているため、必要なGoogle Cloudの設定を完了してから、戻って認証情報の追加を完了することができます。

このワークフローを使用して、Workload FactoryがGoogle Cloud環境内のリソースを検出、分析、管理するために必要な権限を付与します。

認証情報の作成には、以下の3つのステップがあります：

* ステップ1：Workload Factoryに付与する権限レベルを選択します。
* ステップ2：Google Cloudサービスアカウントを作成して検証し、管理するGoogle Cloudプロジェクトを選択します。
* ステップ3：認証情報名を入力し、認証情報を追加します。


.開始する前に
Google Cloudアカウントにログインするには、認証情報が必要です。

.手順
.  https://console.netapp.com/["NetAppコンソール"^]にログインします。
. メニューから、*ワークロード* > *管理* > *認証情報* を選択します。
. 認証情報ページで、「認証情報の追加」を選択します。
. クラウド プロバイダとして *Google Cloud NetApp Volumes* を選択します。
. 「Google Cloud NetApp Volumes 認証情報の追加」ページで、「アクセス許可の設定」の下にある各セクションをすべて入力してください。




[[step-1-create-permission-policies]]
=== ステップ1：アクセス許可ポリシーを作成する

.手順
. *アクセス許可ポリシーの作成*では、*表示、計画、分析*がデフォルトで選択されています。この権限ポリシーにより、Google Cloud NetApp Volumes ストレージプールを表示し、システムの健全性について把握し、システムの適切なアーキテクチャ分析を取得して、コスト削減の可能性を探ることができます。
. オプション：Workload FactoryでGoogle Cloud NetApp Volumesリソースを管理し、構成の問題を修正する場合も、*運用と修復*を選択してください。
. 続行する前に、link:https://docs.netapp.com/us-en/storage-management-google-cloud-netapp-volumes/task-set-up-gcnv.html#set-up-a-service-account["Google Cloud NetApp Volumes のセットアップ"^] でセットアップ手順を確認してください。




[[step-2-create-the-google-cloud-service-account]]
=== ステップ2：Google Cloudサービスアカウントを作成する

.手順
. *Google Cloud 環境をセットアップする* を展開します。
. Google Cloudサービスアカウントを作成するには、表示される手順1～5をすべて完了してください。
. サービスアカウントのメールアドレスをコピーしてください。
. Workload Factoryに戻り、メールアドレスを*GCPサービスアカウント*フィールドに貼り付けて、*認証情報の検証*を選択します。
. 検証が完了したら、*プロジェクト*ドロップダウンから、Workload Factoryで管理するGoogle Cloudプロジェクトを選択します。注：サービスアカウントの認証情報が検証されるまで、プロジェクト一覧は表示されません。




[[step-3-enter-the-credentials-name]]
=== ステップ3：認証情報名を入力します

.手順
. *認証情報名*を展開します。
. *名前*フィールドには、英数字のみを使用して認証情報名を入力してください。特殊文字とスペースは使用できません。
. *追加*を選択します。


.結果
Google Cloud NetApp Volumes の認証情報がアカウントに追加され、サポートされている Workload Factory の操作で使用できるようになります。
