---
sidebar: sidebar 
permalink: admin/well-architected-workloads.html 
keywords: well-architected, best practices, well-architected file system, Amazon FSx for NetApp ONTAP, FSx for ONTAP 
summary: Workload Factoryは、ワークロード構成をスキャンして、信頼性、セキュリティ、運用効率、コスト最適化、およびパフォーマンス効率を評価し、運用効率の向上に役立つ洞察と推奨事項を提供します。 
---
= NetApp Workload Factory が適切に設計されたワークロードをサポートする方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Workload Factoryは、ご利用のクラウド プロバイダのWell-Architected Frameworkに準拠した、信頼性が高く、安全で、効率的かつ対費用効果の高いワークロード構成の維持および運用を支援します。Workload Factoryは、ワークロードの日常的な分析、推奨事項、および自動修正機能を提供し、健全なワークロード運用を促進します。Workload Factoryは、このプロセスを自動化することで、人的ミスを最小限に抑え、ワークロード管理の一貫性を確保します。



[[how-it-works]]
== 仕組み

Workload Factoryは、サポートされているクラウドストレージシステム上で実行されているワークロードを毎日分析します。この分析により、優れたアーキテクチャのステータス、インサイト、および推奨事項が提供されます。

日々の分析が完了すると、デプロイメントのWell-architectedダッシュボードに、構成が「最適化済み」または「最適化されていない」として表示されます。設定に関する問題はカテゴリ別に整理されており、設定に関する問題とその推奨事項の一覧も掲載されています。設定に関する問題については、推奨事項をご確認ください。一部の問題はWorkload Factoryによって自動的に解決されますが、その他の問題は手動での対応が必要です。この場合、Workload Factoryは、推奨される変更を実装するための詳細な手順を提供します。

お客様の環境に適用されない構成の分析を無視することができます。これにより、不要なアラートや不正確な最適化結果を回避できます。

また、組織の標準とNetAppのベストプラクティスに照らして環境を検証するために、平易な言葉でカスタムルールを作成することもできます。ドライランでルールをテストし、各環境で実行するようにスケジュールを設定します。link:https://docs.netapp.com/us-en/console-well-architected/learn-custom-rules.html["カスタムルールについて詳しくはこちらをご覧ください"^]。



[[why-it-matters]]
== 重要な理由

Workload Factory は、継続的な評価と推奨事項、および修復策を組み合わせることで、大規模なストレージ、データベース、および VMware 環境にベストプラクティスを適用します。NetApp Consoleで適用された自動修正により、人的ミスを削減し、統一された管理を確保し、ワークロードインフラストラクチャ全体でパフォーマンスと信頼性を維持します。



[[get-started-with-workload-factory-to-detect-and-fix-workload-misconfigurations]]
== Workload Factory を使用してワークロードの設定ミスを検出して修正する

Workload Factoryを使い始めるには、サインアップして認証情報を追加し、接続を確立してAWSリソースを管理し、Amazon FSx for NetApp ONTAPを使用してワークロードを最適化します。

link:../fsx-storage/quick-start-fsx.html["クイック スタート"]

.関連情報
以下のページでは、さまざまなNetAppストレージソリューションにわたって適切に設計された構成を実装するためのガイダンスを提供します：

* link:../fsx-storage/improve-configurations.html["適切に設計された FSx for ONTAP ファイルシステムを実装する"]
* link:../fsx-databases/optimize-configurations.html["適切に設計されたデータベース構成を実装する"]
* link:../fsx-vmware/view-evs-well-architected.html["適切に設計されたEVS構成を実装する"]
* link:../gcnv/improve-configurations.html["適切に設計されたNetApp Volumes構成を実装する"]
* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-improve-configurations-cvo.html["Microsoft Azureに適切に設計されたCloud Volumes ONTAPシステム構成を実装する"^]

