---
sidebar: sidebar 
permalink: fsx-vmware/deploy-fsx-file-system-evs.html 
keywords: vm workloads, deploy fsx, deploy storage for vms, evs, elastic vmware service 
summary: 推奨されるFSx for ONTAPファイルシステム（場合によっては複数のファイルシステム）がお客様の要件を正確に満たしていることを確認したら、Workload Factoryを使用してAWS環境にシステムをデプロイできます。 
---
= 推奨されるFSx for ONTAPファイルシステムをデプロイします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
推奨されるFSx for ONTAPファイルシステム（場合によっては複数のファイルシステム）がお客様の要件を正確に満たしていることを確認したら、Workload Factoryを使用してAWS環境にシステムをデプロイできます。

Workload Factory アカウントに追加したポリシーと権限に応じて、Workload Factory を使用して FSx for ONTAP ファイルシステムを完全にデプロイできます（読み取り / 書き込みモードを使用）。権限が少ない場合（読み取り専用モード）、または権限がない場合（Basic モード）は、Codebox から CloudFormation テンプレートを使用して、AWS でご自身で FSx for ONTAP ファイルシステムをデプロイする必要があります。



[[requirements]]
== 要件

* Amazon Elastic VMware Serviceのサブスクリプションが必要です。
* AWSアカウントでFSx for ONTAPファイルシステムを作成するために必要な権限が必要です。




[[considerations]]
== 考慮事項

* クイック作成オプションまたは詳細作成オプションを使用できます。詳細作成では、カスタマイズ可能な追加のストレージパラメータがいくつか用意されています。link:../fsx-storage/create-discover-systems.html["これら2つのオプションの提供内容について確認します"]。
* 「Amazon Elastic VMware Service の設定」セクションで、外部データストアに接続する EVS 仮想化環境を選択できます。これにより、デプロイメントに関するベストプラクティスオプションが一部のフィールドに自動的に入力されます。必要に応じてこれらのオプションを変更できます。




[[steps]]
== 手順

. *Review plan*ページの下部で、*Deploy*を選択すると、FSx for ONTAPファイルシステムの作成ページが表示されます。
+
FSx for ONTAPファイルシステムを定義するフィールドのほとんどは、指定した情報に基づいて入力済みですが、このページで入力が必要なフィールドがいくつかあります。

. 「ファイルシステム一般設定」セクションに、以下の情報を入力してください：
+
.. *AWS認証情報*：Workload FactoryにFSx for ONTAPファイルシステムを直接作成するために必要な権限を付与する認証情報を選択または追加します。また、CodeboxからCloudFormationコードを選択し、AWSでFSx for ONTAPファイルシステムをご自身でデプロイすることもできます。
.. *ファイルシステム名*：このFSx for ONTAPファイルシステムに使用する名前を入力します。
.. *タグ*：オプションで、このFSx for ONTAPファイルシステムを分類するためのタグを追加できます。


. 「Amazon Elastic VMware Service 設定」セクションで、「環境 ID」リストから、データストアを接続する EVS 環境を選択します。
+
これにより、以下のフィールドが自動的に入力されます：

+
** *VPC*
** *アベイラビリティゾーン*
** *サブネット*
** *NFSデータストアへのアクセス*セクションで、*EVSホスト管理のみ*オプションを選択した場合、*EVSホスト管理（CIDR）*フィールドは自動的に入力されます。
** *データストアのマウントオプション*セクションで、データストアをEVSクラスタにマウントするように選択した場合、*EVSクラスタVMware vCenter アドレス*と*vSphere管理者認証情報のシークレットARN*フィールドは自動的に入力されます。


. 「ネットワークとセキュリティ」セクションに、以下の情報を入力してください：
+
.. *リージョンとVPC*：FSx for ONTAPファイルシステムが展開されるリージョンとVPCを選択します。
.. *セキュリティ グループ*（高度な作成のみ）：*高度な作成*オプションを使用する場合、すべてのトラフィックがFSx for ONTAPファイルシステムにアクセスできるように、FSx for ONTAP VPCのデフォルトのセキュリティグループを選択できます。新しいセキュリティグループを作成するか、既存のセキュリティグループを選択できます。
+
「EVS NFSデータストアに合わせてセキュリティグループ構成を調整する」オプションを有効にすると、Workload FactoryはEVS NFSデータストアの設定に従ってセキュリティグループを構成します。

+
セキュリティグループにインバウンドルールを追加して、他のAWSサービスがFSx for ONTAPファイルシステムにアクセスできる範囲を制限できます。これにより、オープンになっているサービスの数を減らすことができます。最小限必要なポートとプロトコルは次のとおりです：

+
[cols="15,10,55"]
|===
| プロトコル | ポート | 目的 


| TCP、UDP | 111 | ポートマッパー（NFSリクエストで使用するポートをネゴシエートするために使用される） 


| TCP、UDP | 635 | NFS mountd（NFSマウント要求を受信する） 


| TCP、UDP | 2049 | NFSネットワーク トラフィック 


| TCP、UDP | 4045 | ネットワークロックマネージャ（NLM、lockd） - ロック要求を処理します。 


| TCP、UDP | 4046 | ネットワークステータスモニター（NSM、statd） - ロック管理のためにサーバーの再起動についてNFSクライアントに通知します。 
|===
.. *可用性ゾーン*：可用性ゾーンとサブネットを選択します。
+
ゾーンをまたぐトラフィックに対する料金を回避するには、VMware SDDCがデプロイされているのと同じアベイラビリティゾーンを選択する必要があります。

.. *暗号化*（高度な作成のみ）：*高度な作成*オプションを使用する場合、ドロップダウンからAWS暗号化キー名を選択できます。
.. *NFSデータストアへのアクセス*（高度な作成のみ）：*高度な作成*オプションを使用する場合、すべてのホストがデータストアにアクセスできるかどうか、またはEVS管理ホストのみがデータストアにアクセスできるかどうかを選択できます。


. 「ファイルシステムの詳細」セクションに、以下の情報を入力してください：
+
.. *ONTAP認証情報*：ONTAPのユーザー名とパスワードを入力してください。
.. *ストレージVMの認証情報*（高度な作成のみ）：ストレージVMのパスワードを入力して確認します。パスワードはこのファイルシステム固有のものにすることも、ONTAPの認証情報として入力したパスワードと同じものを使用することもできます。


. 「EVSクラスタ接続」セクションに、以下の情報を入力してください：
+
.. *データストアのマウントオプション*：オプションで、*EVSクラスターにデータストアをマウントする*オプションを有効にすると、データストアがAmazon EVSクラスターに自動的に接続されます。このオプションを選択すると、Workload FactoryはVMware ESXiホストの設定をONTAPのベストプラクティスの推奨事項に一致するように構成します。ファイルシステムをデプロイする前に、*概要*セクションでプランの詳細を確認し、変更された設定を確認できます。
.. *EVSクラスターvSphereコンソールの詳細*：Amazon EVSに接続するVMware vCenterサーバーのIPアドレスまたはFQDNを入力してください。
.. *vSphere管理者資格情報のシークレットARN*：vSphere管理者資格情報のシークレットARNを選択します。これらの資格情報は、データストアをマウントし、推奨されるVMware設定を構成するために使用されます。
+
Amazon EVSがこのリージョンで利用できない場合、またはアカウントに利用可能なシークレットARNのリストを取得する権限がない場合は、シークレットARNの値を手動で入力できます。



. *概要* セクションでは、お客様の情報に基づいて VMware 移行アドバイザーが設計した FSx for ONTAP ファイルシステムおよびデータストアの構成を確認できます。
. FSx for ONTAP ファイルシステムをデプロイするには、*作成* を選択します。この処理には最大2時間かかる場合があります。
+
オプションとして、Codeboxウィンドウで*CloudFormationにリダイレクト*を選択し、CloudFormationスタックを使用してファイルシステムと推奨されるVM構成を作成できます。

+
どちらの場合も、CloudFormationで作成の進行状況を監視できます。





[[result]]
== 結果

FSx for ONTAPファイルシステムがデプロイされました。これで、CodeboxのAWS CloudFormationテンプレートを使用して、推奨されるVM構成をAmazon Elastic VMware Service環境にデプロイできます。
