---
sidebar: sidebar 
permalink: fsx-vmware/deploy-fsx-file-system.html 
keywords: vm workloads, deploy fsx, deploy storage for vms 
summary: 推奨されるFSx for ONTAPファイルシステム（場合によっては複数のファイルシステム）がお客様の要件を正確に満たしていることを確認したら、Workload Factoryを使用してAWS環境にシステムをデプロイできます。 
---
= 推奨されるFSx for ONTAPファイルシステムをデプロイします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
推奨されるFSx for ONTAPファイルシステム（場合によっては複数のファイルシステム）がお客様の要件を正確に満たしていることを確認したら、Workload Factoryを使用してAWS環境にシステムをデプロイできます。

Workload Factory アカウントに追加したポリシーと権限に応じて、Workload Factory を使用して FSx for ONTAP ファイルシステムを完全にデプロイできます（読み取り / 書き込みモードを使用）。権限が少ない場合（読み取り専用モード）、または権限がない場合（Basic モード）は、Codebox からの CloudFormation 情報を使用して、AWS 上でご自身で FSx for ONTAP ファイルシステムをデプロイする必要があります。

.VMware Cloud on AWSへのデプロイメントの要件
* FSx for ONTAP ファイルシステムをデプロイするには、VMware Cloud on AWS Software-Defined Data Center（SDDC）バージョン 1.20 以降を使用している必要があります。
* SDDCのデプロイ時に使用したのと同じVPCにFSx for ONTAPファイルシステムをデプロイしてはいけません。代わりに、VMware Cloud on AWSとAmazon FSx for NetApp ONTAPの統合を有効にするために、お客様が所有する新しいAmazon VPCにデプロイする必要があります。
* SDDCと同じAWSリージョン内にFSx for ONTAPファイルシステムをデプロイする必要があります。


.手順
. *Review plan*ページの下部で、*Deploy*を選択すると、FSx for ONTAPファイルシステムの作成ページが表示されます。
+
FSx for ONTAPファイルシステムを定義するフィールドのほとんどは、指定した情報に基づいて入力済みですが、このページで入力が必要なフィールドがいくつかあります。

+
クイック作成オプションまたは詳細作成オプションを使用できます。詳細作成では、カスタマイズ可能な追加のストレージパラメータがいくつか用意されています。link:../fsx-storage/create-discover-systems.html["これら2つのオプションの提供内容について確認します"]。

. *AWS認証情報*：Workload FactoryにFSx for ONTAPファイルシステムを直接作成するために必要な権限を付与する認証情報を選択または追加します。また、CodeboxからCloudFormationコードを選択し、AWSでFSx for ONTAPファイルシステムをご自身でデプロイすることもできます。
. *ファイルシステム名*：このFSx for ONTAPファイルシステムに使用する名前を入力します。
. *タグ*：オプションでタグを追加して、このFSx for ONTAPファイルシステムを分類できます。
. 「ネットワークとセキュリティ」セクションに、以下の情報を入力してください：
+
.. *リージョンとVPC*：FSx for ONTAPファイルシステムを展開するリージョンとVPCを選択します。
+
VMware Cloud on AWSにデプロイする場合は、VMware Cloud on AWSがデプロイされているVPCとは別のVPCにデプロイするようにしてください。

.. *セキュリティ グループ*：*詳細作成*オプションを使用する場合、FSx for ONTAP VPCのデフォルトのセキュリティグループを選択して、すべてのトラフィックがFSx for ONTAPファイルシステムにアクセスできるようにすることができます。
+
他のAWSサービスがFSx for ONTAPファイルシステムにアクセスできる範囲を制限するインバウンドルールを追加できます。これにより、開いているサービスの数が制限されます。最小限のポートとプロトコルは次のとおりです：

+
[cols="15,10,55"]
|===
| プロトコル | ポート | 目的 


| TCP、UDP | 111 | ポートマッパー（NFSリクエストで使用するポートをネゴシエートするために使用される） 


| TCP、UDP | 635 | NFS mountd（NFSマウント要求を受信する） 


| TCP、UDP | 2049 | NFSネットワーク トラフィック 


| TCP、UDP | 4045 | ネットワークロックマネージャ（NLM、lockd） - ロック要求を処理します。 


| TCP、UDP | 4046 | ネットワークステータスモニター（NSM、statd） - ロック管理のためにサーバーの再起動についてNFSクライアントに通知します。 
|===
.. *アベイラビリティゾーン*：アベイラビリティゾーンとサブネットを選択します。
+
ゾーンをまたぐトラフィックに対する料金を回避するには、VMware SDDCがデプロイされているのと同じアベイラビリティゾーンを選択する必要があります。

.. *暗号化*：*高度な作成*オプションを使用する場合、ドロップダウンからAWS暗号化キー名を選択できます。
.. *データストアのアクセス制御*：*高度な作成*オプションを使用する場合、すべてのホストがデータストアにアクセスできるか、特定のサブネット上の特定のvSphereクラスタノードのみがデータストアにアクセスできるかを選択できます。


. 「ファイルシステムの詳細」セクションに、以下の情報を入力してください：
+
.. *ONTAP認証情報*：ONTAPパスワードを入力して確認します。
.. *ストレージVMの認証情報*（高度な作成のみ）：ストレージVMのパスワードを入力して確認します。パスワードはこのファイルシステム固有のものにすることも、ONTAPの認証情報として入力したパスワードと同じものを使用することもできます。


. *概要* セクションでは、お客様の情報に基づいて VMware 移行アドバイザーが設計した FSx for ONTAP ファイルシステムおよびデータストアの構成を確認できます。
. FSx for ONTAP ファイルシステムをデプロイするには、*作成* を選択します。この処理には最大2時間かかる場合があります。
+
オプションで、Codebox ウィンドウで *CloudFormation にリダイレクト* を選択して、CloudFormation スタックを使用してファイルシステムを作成できます。

+
どちらの場合も、CloudFormationで作成の進行状況を監視できます。



.結果
FSx for ONTAPファイルシステムがデプロイされました。
