---
sidebar: sidebar 
permalink: setup/links-overview.html 
keywords: links, accounts, connectivity, 
summary: Workload Factoryリンクは、Workload Factoryアカウントと1つ以上のクラウドストレージシステムとの間に信頼関係と接続性を確立します。 
---
= NetApp Workload Factory のリンクについて
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Workload Factoryリンクは、Workload Factoryアカウントと1つ以上のクラウドストレージシステムとの間に信頼関係と接続性を確立します。これにより、クラウド プロバイダAPIでは利用できないONTAP REST API呼び出しから直接、ストレージシステムの特定の機能を監視および管理できるようになります。

Workload Factory を使い始めるのにリンクは必要ありませんが、場合によっては、Workload Factory のすべての機能とワークロード機能を有効にするためにリンクを作成する必要があります。



[[why-links-are-beneficial]]
== リンクが有益な理由

リンクは、クラウド プロバイダのAPIを通じてネイティブには利用できない操作をWorkload Factoryが実行できるようにするため、有益です。リンクによって高度なONTAP機能と自動化が有効になり、クラウド ストレージ システムの管理が強化されます。

リンクを使用するメリットをいくつかご紹介します：

* このリンクにより、NetApp Consoleからクラウド ストレージ システムに直接ONTAPコマンドを送信できるようになり、クラウド プロバイダがネイティブに提供する以上の高度なONTAP機能を利用できるようになります。
* リンクは、リモートのサーバーレス関数を活用して、イベントに応じてコードを実行します。このサーバーレス方式では、VPC内でインスタンスを実行する必要性がなくなります。




[[how-links-work]]
== リンクの仕組み

リンクは、AWS LambdaやOracle Cloud Infrastructure Functionsなどのリモートサーバレスコンピューティングサービスを活用します。これらのサービスは、イベントに応じてコードを実行し、そのコードに必要なコンピューティングリソースを自動的に管理します。作成したリンクはお客様のNetAppアカウントの一部であり、対応するクラウド プロバイダアカウントに関連付けられます。

リンクを作成した後、それを1つまたは複数のクラウドストレージシステムに関連付けることができます。各クラウドストレージシステムは、同じNetAppアカウント内の1つのリンクにのみ関連付けることができます。複数のNetAppアカウントがある場合、単一のクラウドストレージシステムを、異なるNetAppアカウントの追加のリンクに関連付けることができます。

クラウドストレージシステム用のNetApp Consoleのリンクページから、リンクを作成して関連付けます。

Workload Factoryの認証情報サービスに保存されている認証情報、またはクラウド プロバイダの認証情報サービスを使用して、リンクを認証できます。Workload Factoryは認証モードの変更をサポートしていません。



[[costs]]
== 費用

お客様のクラウド プロバイダのサーバーレスコンピューティングサービスが実行する各トランザクションには、料金が発生します。2つのシステム間のプロキシとして機能するため、サービスがファイルシステム上のONTAP REST APIにリクエストを送信する際、およびWorkload Factoryに応答を返す際に料金が発生します。

* link:https://aws.amazon.com/lambda/pricing/["AWS Lambdaの使用に関連するコストについて詳しくはこちらをご覧ください。"^]
* link:https://www.oracle.com/cloud/cloud-native/functions/["Oracle Cloud Infrastructure Functionsの使用に関連するコストについて詳しくはこちらをご覧ください"^]




[[when-a-link-is-required]]
== リンクが必要な場合

Workload Factoryは、一部の情報を表示したり、一部のタスクを実行したりするためにリンクを必要とします。リンクを必要とする操作を実行しようとした際に、クラウドストレージシステムとリンクを関連付けていない場合、Workload Factoryは操作にリンクが必要であることを通知します。

リンクが必要な機能は以下のとおりです：

* 予防保守、信頼性、およびコストパフォーマンスの最適化のためのクラウドストレージシステム構成の適切なアーキテクチャ状態
* ONTAP EMS イベントの監視とアラート
* NetApp Autonomous Ransomware Protection（ARP/AI）
* クラウドストレージシステム全体にわたる包括的な容量監視機能の強化
* ボリュームとStorage VMのデータレプリケーション、管理、および監視
* SMB/CIFS共有およびNFSエクスポートポリシーのプロビジョニングと管理
* クラウドストレージシステムにおけるiSCSIボリュームの管理
* カスタム保護SLAのためのスナップショットポリシーの作成と管理
* 自動容量管理のためのinode管理機能強化
* 柔軟なスケーリングのためのボリュームの自動拡張
* クローン作成と管理により、即座にその場でデータクローンを作成できます。
* システムバージョンなどの追加メトリクスをクラウドストレージシステムから直接表示します
* ストレージVMとクラスタLIFの詳細（ロール、エンドポイント、ノード、IPアドレス、ステータスなど）の表示




[[related-information]]
== 関連情報

次のリンクを作成および関連付ける方法を確認します：

* link:../fsx-storage/create-link.html["Amazon FSx for NetApp ONTAP"]
* link:../oci/create-link.html["OCI NetAppストレージサービス"]

